let suiviData = [
  {
    "id": 1,
    "representant": "Mme yasmina",
    "nom": "",
    "mode_retour": "contact Mr karim",
    "activite": "ECOLE MONTESSORI",
    "contact": "709 23 80 68",
    "type_bien": "VILLA",
    "action": "location",
    "budget": 60000,
    "superficie": "",
    "zone": "",
    "type_accompagnement": "creation de la societe, business plan, commercialisation, gestion des travaux et amenagement, etude de marche, etude concurrentielle, marketing digital dossier de financement du projet",
    "prix_alloue": "",
    "services_clotures": "Proccuration, mandat exclusif de gestion, etude de marche, prospection, contrat de bail, devis des travaux et d'amenagement, creation de logos et image de marque",
    "services_a_cloturer": "l'autorisation d'exploitation, travaux, dossier de financement, business plan, marketing digital",
    "ok_nok": "OK",
    "annexes": "",
    "ca_previsionnel": 120000,
    "ca_realise": 100000,
    "total_ca": "",
    "status": "Active",
    "created_date": "2024/02/02",
    "update_date": "2024/02/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "id": 2,
    "representant": "Mme HASSNA",
    "nom": "Atlas capital",
    "mode_retour": "site web",
    "activite": "Cabinet d'assurance",
    "contact": 662830415,
    "type_bien": "plateau bureau",
    "action": "location",
    "budget": 6100,
    "superficie": 54,
    "zone": "NEJMA",
    "type_accompagnement": "prospection",
    "prix_alloue": "",
    "services_clotures": "CONTRAT CLOTUREE",
    "services_a_cloturer": "RAS",
    "ok_nok": "OK",
    "annexes": "",
    "ca_previsionnel": 12200,
    "ca_realise": 12200,
    "total_ca": "",
    "status": "Active",
    "created_date": "2024/02/02",
    "update_date": "2024/02/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "id": 3,
    "representant": "Mr Rachid",
    "nom": "",
    "mode_retour": "contact Mr karim",
    "activite": "promotion immobiliere",
    "contact": 33777373060,
    "type_bien": "TERRAIN",
    "action": "achat",
    "budget": "",
    "superficie": 400,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 0,
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/02/02",
    "update_date": "2024/02/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "id": 4,
    "representant": "Mr EL BAKKOURI",
    "nom": "",
    "mode_retour": "contact Mr karim",
    "activite": "RESTAURATION",
    "contact": 33609716096,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 10000,
    "superficie": 37,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "programme d'accompagnement",
    "prix_alloue": "",
    "services_clotures": "propositions, visites de trois locaux, signature des bons de visites et avis de recherche",
    "services_a_cloturer": "Visite sur place le 20/03/2024",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 20000,
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/02/02",
    "update_date": "2024/02/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "id": 5,
    "representant": "zin eddine abidine",
    "nom": "",
    "mode_retour": "contact Mr karim",
    "activite": "promotion immobiliere",
    "contact": "44 7487 746205",
    "type_bien": "TERRAIN",
    "action": "achat",
    "budget": 2000000,
    "superficie": 1000,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee, visite sur place des terrains",
    "services_a_cloturer": "etude de faisabilite des terrains",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 4000000,
    "ca_realise": "",
    "total_ca": "",
    "status": "Pause",
    "created_date": "2024/02/02",
    "update_date": "2024/02/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "id": 6,
    "representant": "Mr TOUMI",
    "nom": "TANGER TECH",
    "mode_retour": "contact Mr karim",
    "activite": "",
    "contact": "636 06 04 73",
    "type_bien": "VILLA",
    "action": "location",
    "budget": 50000,
    "superficie": 600,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "recherche en cours",
    "services_a_cloturer": "propositions",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 100000,
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "id": 7,
    "representant": "Mr Anas",
    "nom": "",
    "mode_retour": "site web",
    "activite": "visite technique",
    "contact": 661175018,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 60000,
    "superficie": 400,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "recherche en cours",
    "services_a_cloturer": "propositions",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 120000,
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "id": 8,
    "representant": "Mme HOUDA",
    "nom": "",
    "mode_retour": "sarouty",
    "activite": "produits cosmetics",
    "contact": 667079410,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 15000,
    "superficie": "",
    "zone": "CENTRE VILLE",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "recherche en cours",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 30000,
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "id": 9,
    "representant": "Mr EL JAMALI",
    "nom": "cabinet service",
    "mode_retour": "contact Mr karim",
    "activite": "ECOLE MONTESSORI",
    "contact": "7 7 63 70 64 7 2",
    "type_bien": "VILLA",
    "action": "location",
    "budget": 60000,
    "superficie": "",
    "zone": "CENTRE VILLE",
    "type_accompagnement": "creation de la societe, business plan, commercialisation, gestion des travaux et amenagement, etude de marche, etude concurrentielle, marketing digital dossier de financement du projet",
    "prix_alloue": "",
    "services_clotures": "contrat de bail, devis des travaux et d'amenagement, prospection, etude de marche",
    "services_a_cloturer": "l'autorisation d'exploitation, travaux, dossier de financement, business plan, marketing digital",
    "ok_nok": "OK",
    "annexes": "",
    "ca_previsionnel": 120000,
    "ca_realise": 100000,
    "total_ca": "",
    "status": "Active",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "id": 10,
    "representant": "Mr Hassane",
    "nom": "",
    "mode_retour": "contact Mr karim",
    "activite": "Achat / Vente de Terrains",
    "contact": "7 7 63 70 64 7 2",
    "type_bien": "TERRAIN",
    "action": "achat",
    "budget": 4000000,
    "superficie": 2000,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "PROPOSITION ENVOYEE",
    "services_a_cloturer": "Etude de faisabilite des terrains",
    "ok_nok": "OK",
    "annexes": "",
    "ca_previsionnel": 8000000,
    "ca_realise": "",
    "total_ca": "",
    "status": "Active",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "id": 11,
    "representant": "Mr NABIL",
    "nom": "",
    "mode_retour": "contact Mr karim",
    "activite": "RECHERCHE INVESTISSEUR",
    "contact": 775940390,
    "type_bien": "CABINET D'ARCHITECTURE",
    "action": "location",
    "budget": 25000,
    "superficie": "",
    "zone": "TANGER MARINA",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "recherche en cours",
    "services_a_cloturer": "propositions",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 50000,
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "id": 12,
    "representant": "Mr Karim",
    "nom": "",
    "mode_retour": "contact Mr karim",
    "activite": "CABINET D'ARCHITECTURE",
    "contact": 770122999,
    "type_bien": "CABINET D'ARCHITECTURE",
    "action": "location",
    "budget": 5000,
    "superficie": "",
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "",
    "services_a_cloturer": "contrat de bail",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 10000,
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  }
];
export default suiviData;
